# Generated by Django 6.0.5 on 2026-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
