# Generated by Django 6.0.5 on 2026-06-02 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chat_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='share_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
